import type { FieldDef } from "../shared/types.ts";

export const ENERGY_COSTS_FIELDS: FieldDef[] = [
	{
		path: "energy.costs.move_cost",
		label: "Move Cost",
		min: 0,
		max: 10,
		step: 0.01,
		testId: "config-field-energy-costs-move-cost",
		defaultValue: 0.2,
		tooltip: "Energy subtracted each time a creature moves to an adjacent cell",
	},
	{
		path: "energy.costs.eat_cost",
		label: "Eat Cost",
		min: 0,
		max: 10,
		step: 0.01,
		defaultValue: 0.0,
		tooltip: "Energy subtracted when a creature eats food from its cell",
	},
	{
		path: "energy.costs.noop_cost",
		label: "Noop Cost",
		min: 0,
		max: 10,
		step: 0.01,
		defaultValue: 0.05,
		tooltip: "Energy subtracted when a creature takes no action",
	},
	{
		path: "energy.costs.reproduce_cost",
		label: "Reproduce Cost",
		min: 0,
		max: 50,
		step: 0.1,
		defaultValue: 0.1,
		tooltip: "Energy subtracted from parent when reproduction occurs",
	},
	{
		path: "energy.costs.failed_action_penalty",
		label: "Failed Action Penalty",
		min: 0,
		max: 20,
		step: 0.1,
		defaultValue: 1.0,
		testId: "config-field-energy-costs-failed-action-penalty",
		tooltip: "Additional energy penalty when an action fails (move blocked, eat empty cell, etc.)",
	},
];
