import type { BooleanFieldDef, FieldDef } from "../shared/types.ts";

export const MUTATION_NEWBORN_FIELDS: FieldDef[] = [
	{
		path: "mutation.topology_new_node_birth.graph_backend_chance",
		label: "Birth Graph Chance",
		min: 0,
		max: 1,
		step: 0.01,
		testId: "config-field-mutation-birth-graph-backend-chance",
		defaultValue: 0.5,
		tooltip: "Chance that AddNode/SpliceNode newborns use Graph backend instead of minimal VM",
	},
	{
		path: "mutation.topology_new_node_birth.graph_initialized_chance",
		label: "Birth Init Chance",
		min: 0,
		max: 1,
		step: 0.01,
		testId: "config-field-mutation-birth-graph-initialized-chance",
		defaultValue: 0.8,
		tooltip: "Given Graph newborn, chance to initialize one input_ref and one CustomOutput wire",
	},
	{
		path: "mutation.topology_new_node_birth.graph_compute_gate_chance",
		label: "Birth Compute Chance",
		min: 0,
		max: 1,
		step: 0.01,
		testId: "config-field-mutation-birth-graph-compute-gate-chance",
		defaultValue: 0.5,
		tooltip:
			"Given initialized Graph newborn, chance to route the sink through one newborn compute gate",
	},
];

export const MUTATION_FIELDS: FieldDef[] = [
	{
		path: "mutation.mutation_probability",
		label: "Mutation Prob.",
		min: 0,
		max: 1,
		step: 0.001,
		testId: "config-field-mutation-mutation-probability",
		defaultValue: 0.44,
		tooltip: "Probability that a newborn genome undergoes mutation",
	},
	{
		path: "mutation.per_birth_mutation_events_min",
		label: "Min Events/Birth",
		min: 0,
		max: 20,
		step: 1,
		testId: "config-field-mutation-events-min",
		defaultValue: 1,
		tooltip: "Minimum number of mutation events per birth when mutation triggers",
	},
	{
		path: "mutation.per_birth_mutation_events_max",
		label: "Max Events/Birth",
		min: 0,
		max: 20,
		step: 1,
		testId: "config-field-mutation-events-max",
		defaultValue: 10,
		tooltip: "Maximum number of mutation events per birth when mutation triggers",
	},
	{
		path: "mutation.per_birth_mutation_event_continuation_probability",
		label: "Continue Events Prob.",
		min: 0,
		max: 1,
		step: 0.01,
		testId: "config-field-mutation-event-continuation-probability",
		defaultValue: 0.2,
		tooltip: "After the minimum, chance to request another mutation event up to the maximum",
	},
	{
		path: "mutation.mesh_layer_probability",
		label: "Mesh Layer Prob.",
		min: 0,
		max: 1,
		step: 0.01,
		testId: "config-field-mutation-mesh-layer-probability",
		defaultValue: 0.2,
		tooltip: "Probability of adding a mesh layer during genome mutation",
	},
	{
		path: "mutation.genome_size_cap",
		label: "Genome Size Cap",
		min: 1,
		max: 5000,
		step: 1,
		testId: "config-field-mutation-genome-size-cap",
		defaultValue: 1200,
		tooltip: "Maximum genome size before size pressure suppresses growth mutations",
	},
	{
		path: "mutation.phenotype.channel_step",
		label: "Channel Step",
		min: 1,
		max: 50,
		step: 1,
		testId: "config-field-mutation-channel-step",
		defaultValue: 1,
		tooltip: "RGB step size applied per tick to the active color channel",
	},
	{
		path: "mutation.phenotype.polarity_flip_chance",
		label: "Polarity Flip",
		min: 0,
		max: 1,
		step: 0.001,
		testId: "config-field-mutation-polarity-flip",
		defaultValue: 0.0002,
		tooltip: "Probability of reversing the drift direction of the active color channel",
	},
	{
		path: "mutation.phenotype.channel_change_chance",
		label: "Channel Switch",
		min: 0,
		max: 1,
		step: 0.001,
		testId: "config-field-mutation-channel-change",
		defaultValue: 0.001,
		tooltip: "Probability of switching to a different active color channel (R/G/B)",
	},
	{
		path: "mutation.action_queue_cap",
		label: "Action Queue Cap",
		min: 1,
		max: 16,
		step: 1,
		testId: "config-field-mutation-action-queue-cap",
		defaultValue: 4,
		tooltip: "Maximum number of actions in the creature action queue",
	},
	...MUTATION_NEWBORN_FIELDS,
	{
		path: "mutation.reachable_bias.topology",
		label: "Bias: Topology",
		min: 0,
		max: 1,
		step: 0.01,
		testId: "config-field-mutation-reachable-bias-topology",
		defaultValue: 0,
		tooltip:
			"Chance to prefer reachable nodes; zero selects uniformly among eligible nodes for topology mutations",
	},
	{
		path: "mutation.reachable_bias.vm",
		label: "Bias: VM",
		min: 0,
		max: 1,
		step: 0.01,
		testId: "config-field-mutation-reachable-bias-vm",
		defaultValue: 0,
		tooltip:
			"Chance to prefer reachable nodes; zero selects uniformly among eligible nodes for VM mutations",
	},
	{
		path: "mutation.reachable_bias.graph",
		label: "Bias: Graph",
		min: 0,
		max: 1,
		step: 0.01,
		testId: "config-field-mutation-reachable-bias-graph",
		defaultValue: 0,
		tooltip:
			"Chance to prefer reachable nodes; zero selects uniformly among eligible nodes for graph mutations",
	},
	{
		path: "mutation.reachable_bias.input_ref",
		label: "Bias: Input Ref",
		min: 0,
		max: 1,
		step: 0.01,
		testId: "config-field-mutation-reachable-bias-input-ref",
		defaultValue: 0,
		tooltip:
			"Chance to prefer reachable nodes; zero selects uniformly among eligible nodes for input reference mutations",
	},
];

export const MUTATION_TOGGLES: BooleanFieldDef[] = [
	{
		path: "mutation.genome_size_pressure_enabled",
		label: "Genome Size Pressure",
		testId: "config-field-mutation-genome-size-pressure-enabled",
		defaultValue: false,
		tooltip: "When enabled, genomes near the size cap are less likely to gain growth mutations",
	},
];

export const MUTATION_ALL_FIELDS: (FieldDef | BooleanFieldDef)[] = [
	...MUTATION_FIELDS,
	...MUTATION_TOGGLES,
];
