import type { BooleanFieldDef, FieldDef } from "../shared/types.ts";

export const MUTATION_FIELDS: FieldDef[] = [
	{
		path: "mutation.mutation_probability",
		label: "Mutation Prob.",
		min: 0,
		max: 1,
		step: 0.001,
		testId: "config-field-mutation-mutation-probability",
		defaultValue: 0.303,
		tooltip: "Probability that a newborn genome undergoes mutation",
	},
	{
		path: "mutation.per_birth_mutation_events_min",
		label: "Min Events/Birth",
		min: 0,
		max: 20,
		step: 1,
		testId: "config-field-mutation-events-min",
		defaultValue: 1,
		tooltip: "Minimum number of mutation events per birth when mutation triggers",
	},
	{
		path: "mutation.per_birth_mutation_events_max",
		label: "Max Events/Birth",
		min: 0,
		max: 20,
		step: 1,
		testId: "config-field-mutation-events-max",
		defaultValue: 10,
		tooltip: "Maximum number of mutation events per birth when mutation triggers",
	},
	{
		path: "mutation.mesh_layer_probability",
		label: "Mesh Layer Prob.",
		min: 0,
		max: 1,
		step: 0.01,
		testId: "config-field-mutation-mesh-layer-probability",
		defaultValue: 0.2,
		tooltip: "Probability of adding a mesh layer during genome mutation",
	},
	{
		path: "mutation.genome_size_cap",
		label: "Genome Size Cap",
		min: 1,
		max: 5000,
		step: 1,
		testId: "config-field-mutation-genome-size-cap",
		defaultValue: 1200,
		tooltip: "Maximum genome size before size pressure suppresses growth mutations",
	},
	{
		path: "mutation.phenotype.channel_step",
		label: "Channel Step",
		min: 1,
		max: 50,
		step: 1,
		testId: "config-field-mutation-channel-step",
		defaultValue: 1,
		tooltip: "RGB step size applied per tick to the active color channel",
	},
	{
		path: "mutation.phenotype.polarity_flip_chance",
		label: "Polarity Flip",
		min: 0,
		max: 1,
		step: 0.001,
		testId: "config-field-mutation-polarity-flip",
		defaultValue: 0.0002,
		tooltip: "Probability of reversing the drift direction of the active color channel",
	},
	{
		path: "mutation.phenotype.channel_change_chance",
		label: "Channel Switch",
		min: 0,
		max: 1,
		step: 0.001,
		testId: "config-field-mutation-channel-change",
		defaultValue: 0.001,
		tooltip: "Probability of switching to a different active color channel (R/G/B)",
	},
	{
		path: "mutation.action_queue_cap",
		label: "Action Queue Cap",
		min: 1,
		max: 16,
		step: 1,
		testId: "config-field-mutation-action-queue-cap",
		defaultValue: 4,
		tooltip: "Maximum number of actions in the creature action queue",
	},
];

export const MUTATION_TOGGLES: BooleanFieldDef[] = [
	{
		path: "mutation.genome_size_pressure_enabled",
		label: "Genome Size Pressure",
		testId: "config-field-mutation-genome-size-pressure-enabled",
		defaultValue: true,
		tooltip:
			"When enabled, genomes near the size cap are less likely to gain growth mutations",
	},
];

export const MUTATION_ALL_FIELDS: (FieldDef | BooleanFieldDef)[] = [
	...MUTATION_FIELDS,
	...MUTATION_TOGGLES,
];
