import type { FieldDef } from "../shared/types.ts";

export const RUNTIME_FIELDS: FieldDef[] = [
	{
		path: "runtime.max_mesh_hops",
		label: "Max Mesh Hops",
		min: 1,
		max: 1024,
		step: 1,
		defaultValue: 1024,
		tooltip: "Maximum signal propagation hops through the genome mesh per tick",
	},
	{
		path: "runtime.max_vm_steps",
		label: "Max VM Steps",
		min: 1,
		max: 10000,
		step: 1,
		defaultValue: 10000,
		tooltip: "Maximum VM instructions executed per creature per tick",
	},
	{
		path: "runtime.max_graph_relax_iters",
		label: "Graph Relax Iters (inactive)",
		min: 1,
		max: 100,
		step: 1,
		defaultValue: 15,
		tooltip:
			"Retained configuration field; graphs now evaluate once per visit on the world-tick clock",
	},
	{
		path: "runtime.graph_convergence_epsilon",
		label: "Convergence Epsilon (inactive)",
		min: 0.0001,
		max: 1,
		step: 0.0001,
		defaultValue: 0.001,
		tooltip:
			"Retained configuration field; graphs now evaluate once per visit on the world-tick clock",
	},
	{
		path: "runtime.graph_convergence_stable_passes",
		label: "Stable Passes (inactive)",
		min: 1,
		max: 10,
		step: 1,
		defaultValue: 2,
		tooltip:
			"Retained configuration field; graphs now evaluate once per visit on the world-tick clock",
	},
	{
		path: "runtime.graph_node_base_cost",
		label: "Node Base Cost",
		min: 0,
		max: 100,
		step: 0.1,
		defaultValue: 0.00001,
		tooltip: "Base compute cost per graph node during evaluation",
	},
	{
		path: "runtime.vm.opcode_cost_multiplier",
		label: "Opcode Cost Mult.",
		min: 0,
		max: 10,
		step: 0.1,
		defaultValue: 0.000001,
		tooltip: "Multiplier applied to each VM opcode's compute cost",
	},
	{
		path: "runtime.vm.step_ramp_allowance",
		label: "Step Ramp Allowance",
		min: 0,
		max: 10000,
		step: 1,
		defaultValue: 100,
		tooltip: "Free VM instructions per node dispatch before the activity ramp starts charging",
	},
	{
		path: "runtime.vm.step_ramp_cost",
		label: "Step Ramp Cost",
		min: 0,
		max: 1,
		step: 0.000001,
		defaultValue: 0.000001,
		tooltip:
			"Extra energy per excess step, per step past the allowance, within one VM node dispatch",
	},
	{
		path: "runtime.plasticity_update_cost",
		label: "Plasticity Update Cost",
		min: 0,
		max: 10,
		step: 0.001,
		defaultValue: 0.0,
		tooltip: "Energy cost per plasticity weight update during neural processing",
	},
	{
		path: "runtime.reward_learning_cost",
		label: "Reward Learning Cost",
		min: 0,
		max: 10,
		step: 0.001,
		defaultValue: 0.0,
		tooltip: "Energy cost per reward-modulated weight update during learning",
	},
	{
		path: "runtime.max_actions_per_turn",
		label: "Max Actions/Turn",
		min: 1,
		max: 20,
		step: 1,
		defaultValue: 10,
		tooltip: "Maximum number of actions a creature can queue per turn",
	},
	{
		path: "runtime.perception.vision_radius",
		label: "Vision Radius",
		min: 1,
		max: 8,
		step: 1,
		defaultValue: 5,
		tooltip: "Vision radius for extended perception area summaries",
	},
];
