import type { FieldDef } from "../shared/types.ts";

export const RUNTIME_FIELDS: FieldDef[] = [
	{
		path: "runtime.max_mesh_hops",
		label: "Max Mesh Hops",
		min: 1,
		max: 1024,
		step: 1,
		defaultValue: 1024,
		tooltip: "Maximum signal propagation hops through the genome mesh per tick",
	},
	{
		path: "runtime.max_vm_steps",
		label: "Max VM Steps",
		min: 1,
		max: 10000,
		step: 1,
		defaultValue: 10000,
		tooltip: "Maximum VM instructions executed per creature per tick",
	},
	{
		path: "runtime.max_graph_relax_iters",
		label: "Graph Relax Iters",
		min: 1,
		max: 100,
		step: 1,
		defaultValue: 15,
		tooltip: "Maximum iterations for graph relaxation convergence",
	},
	{
		path: "runtime.graph_convergence_epsilon",
		label: "Convergence Epsilon",
		min: 0.0001,
		max: 1,
		step: 0.0001,
		defaultValue: 0.001,
		tooltip: "Threshold below which graph relaxation is considered converged",
	},
	{
		path: "runtime.graph_convergence_stable_passes",
		label: "Stable Passes",
		min: 1,
		max: 10,
		step: 1,
		defaultValue: 2,
		tooltip: "Consecutive stable passes required before declaring convergence",
	},
	{
		path: "runtime.graph_node_base_cost",
		label: "Node Base Cost",
		min: 0,
		max: 100,
		step: 0.1,
		defaultValue: 0.00001,
		tooltip: "Base compute cost per graph node during evaluation",
	},
	{
		path: "runtime.vm.opcode_cost_multiplier",
		label: "Opcode Cost Mult.",
		min: 0,
		max: 10,
		step: 0.1,
		defaultValue: 0.000001,
		tooltip: "Multiplier applied to each VM opcode's compute cost",
	},
];
