[package]
name = "v3-core"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
slotmap = { workspace = true }
noise = "0.9"

[features]
dhat-heap = ["dep:dhat"]

[dependencies.dhat]
version = "0.3"
optional = true

[dev-dependencies]
serde_json = { workspace = true }
criterion = "0.5"

[[bench]]
name = "tick"
harness = false
