pub mod action_decode;
pub(crate) mod cgp_graph;
pub(crate) mod cgp_graph_effects;
pub mod graph;
pub mod inputs;
pub mod mesh;
pub(crate) mod plasticity;
pub mod trace;
pub mod traced_graph;
pub mod traced_mesh;
pub mod traced_vm;
pub mod types;
pub mod vm;
pub use mesh::execute_creature_mesh;
pub use types::{sanitize_f32, MeshOutput, MeshSideOutputs, NodeResult, OUTPUT_SLOT_COUNT};
